language: python
sudo: false
cache:
  directories:
    - $DEPS
env:
  global:
    - DEPS=$HOME/node_modules
    - PATH=$DEPS/.bin:$PATH
install: |
  DIR=$(pwd)
  cd $HOME
  npm install jsonlint
  cd $DIR
script: |
  jsonlint -q db.json
  jsonlint -q tags.json
