language: python
sudo: false
cache:
  directories:
    - $DEPS
env:
  global:
    - DEPS=$HOME/node_modules
    - PATH=$DEPS/.bin:$PATH
install: |
  if [ ! -e "$DEPS/.bin/jsonlint" ]; then
    DIR=$(pwd)
    cd $HOME
    npm install jsonlint
    cd $DIR
  fi
script: ./tests/test.sh
